name: Generate sitemap

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate sitemap
        run: npm run generate-sitemap

      - name: Upload sitemap artifact
        uses: actions/upload-artifact@v4
        with:
          name: sitemap
          path: public/sitemap.xml
