name: Generate sitemap

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate sitemap
        run: npm run generate-sitemap

      - name: Validate generated sitemap XML
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libxml2-utils
          xmllint --noout public/sitemap.xml

      - name: Create Pull Request with generated sitemap
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(sitemap): update generated sitemap"
          branch: "sitemap/generated-${{ github.run_id }}"
          title: "chore(sitemap): update generated sitemap"
          body: |
            This PR contains the sitemap generated by CI on `${{ github.run_date }}`.
            The sitemap was validated with `xmllint` before creating this PR.
          labels: automated, sitemap
